#!/usr/bin/env python3
"""Generate description/kuka_arm.urdf from config/robot.yaml.

The URDF is derived only from the DH table and joint limits, so it can never
disagree with the controller's own forward kinematics. ``--check`` verifies
that the checked-in file is up to date and matches forward_kinematics().

Conventions (also written into the URDF header):
  * Units: metres / radians (URDF standard). robot.yaml uses mm / degrees.
  * URDF joint zero = servo centre (90°):  servo_deg = degrees(q) + 90.
    So the all-zero configuration is the middle of every servo's range and
    not an end stop, and limits are symmetric-ish around zero.
  * Only arm joints (type: revolute) become URDF joints. The gripper (J5)
    does not move the TCP; its DH row becomes the fixed ``tool0`` frame.
  * No inertials: robot.yaml publishes no masses. Add a ``dynamics`` section
    (e.g. from CAD) and they will be emitted.

Usage:
  python3 tools/generate_urdf.py            # write description/kuka_arm.urdf
  python3 tools/generate_urdf.py --check    # exit 1 if out of date / mismatch
"""
import argparse
import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import config  # noqa: E402
from app.kinematics import forward_kinematics  # noqa: E402

OUTPUT = ROOT / "description" / "kuka_arm.urdf"
ROBOT_NAME = "kuka_arm"
SERVO_ZERO_DEG = 90.0
MM = 1e-3
LINK_RADIUS_M = 0.008


def _rot_z(deg: float) -> np.ndarray:
    t = math.radians(deg)
    T = np.eye(4)
    T[:2, :2] = [[math.cos(t), -math.sin(t)], [math.sin(t), math.cos(t)]]
    return T


def _dh_fixed(a: float, alpha: float, d: float) -> np.ndarray:
    """Tz(d)·Tx(a)·Rx(alpha): the constant part of one DH row (mm → m)."""
    al = math.radians(alpha)
    T = np.eye(4)
    T[:3, :3] = [[1, 0, 0], [0, math.cos(al), -math.sin(al)], [0, math.sin(al), math.cos(al)]]
    T[0, 3] = a * MM
    T[2, 3] = d * MM
    return T


def _rpy(R: np.ndarray) -> tuple:
    """URDF rpy (fixed-axis X, Y, Z) with R = Rz(y)·Ry(p)·Rx(r)."""
    sy = math.hypot(R[0, 0], R[1, 0])
    if sy > 1e-9:
        return (math.atan2(R[2, 1], R[2, 2]), math.atan2(-R[2, 0], sy), math.atan2(R[1, 0], R[0, 0]))
    return (math.atan2(-R[1, 2], R[1, 1]), math.atan2(-R[2, 0], sy), 0.0)


def _fmt(values) -> str:
    out = []
    for v in values:
        v = 0.0 if abs(v) < 1e-12 else v
        out.append(f"{v:.12g}")
    return " ".join(out)


def _origin(T: np.ndarray) -> str:
    return f'<origin xyz="{_fmt(T[:3, 3])}" rpy="{_fmt(_rpy(T[:3, :3]))}"/>'


def _link_visual(offset: np.ndarray) -> list:
    """A cylinder from the link origin to the next joint (pure visualisation)."""
    length = float(np.linalg.norm(offset))
    if length < 1e-6:
        return []
    z = offset / length
    # Rotation that maps the cylinder's +Z onto the link direction.
    axis = np.cross([0, 0, 1], z)
    s, c = np.linalg.norm(axis), float(z[2])
    if s < 1e-9:
        R = np.eye(3) if c > 0 else np.diag([1, -1, -1])
    else:
        k = axis / s
        K = np.array([[0, -k[2], k[1]], [k[2], 0, -k[0]], [-k[1], k[0], 0]])
        R = np.eye(3) + s * K + (1 - c) * K @ K
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = offset / 2
    return [
        "    <visual>",
        f"      {_origin(T)}",
        f'      <geometry><cylinder radius="{LINK_RADIUS_M}" length="{length:.9g}"/></geometry>',
        '      <material name="link_grey"/>',
        "    </visual>",
    ]


def build_urdf(cfg: dict) -> str:
    joints = cfg["joints"]
    types = cfg["servos"]["types"]
    dynamics = cfg.get("dynamics") or {}

    lines = [
        '<?xml version="1.0"?>',
        "<!-- GENERATED by tools/generate_urdf.py from config/robot.yaml. Do not edit by hand. -->",
        "<!-- Units: m / rad. URDF joint zero = servo centre: servo_deg = degrees(q) + 90. -->",
        "<!-- The gripper (type: gripper) is not a kinematic joint; its DH row is the fixed tool0 frame. -->",
    ]
    if not dynamics:
        lines.append("<!-- No inertials: robot.yaml publishes no masses. Add a 'dynamics' section to emit them. -->")
    lines += [
        f'<robot name="{ROBOT_NAME}">',
        '  <material name="link_grey"><color rgba="0.3 0.3 0.3 1"/></material>',
    ]

    link_names = ["base_link"]
    link_bodies = {"base_link": []}
    joint_blocks = []
    fixed = np.eye(4)           # transform from the current link frame onwards
    current = "base_link"

    for i, (a, alpha, d, offset) in enumerate(cfg["dh_parameters"]):
        j = joints[i] if i < len(joints) else None
        if j is not None and config.joint_type(j) == "revolute":
            link_bodies[current] += _link_visual(fixed[:3, 3])
            child = f"link_{j['name'].lower()}"
            stype = types.get(j.get("servo_type", ""), {})
            lower = math.radians(j["min_angle"] - SERVO_ZERO_DEG)
            upper = math.radians(j["max_angle"] - SERVO_ZERO_DEG)
            velocity = math.radians(stype.get("max_speed_dps", 60))
            effort = stype.get("torque_nm", 1.0)
            joint_blocks += [
                f'  <joint name="{j["name"].lower()}" type="revolute">',
                f"    <!-- {j['name']} {j.get('label', '')}: PCA9685 ch{j['channel']}, "
                f"{j.get('servo_type', '')}, servo {j['min_angle']}..{j['max_angle']} deg, "
                f"home {j['home_angle']} deg -->",
                f'    <parent link="{current}"/>',
                f'    <child link="{child}"/>',
                f"    {_origin(fixed @ _rot_z(offset + SERVO_ZERO_DEG))}",
                '    <axis xyz="0 0 1"/>',
                f'    <limit lower="{lower:.12g}" upper="{upper:.12g}" effort="{effort:.9g}" velocity="{velocity:.12g}"/>',
                "  </joint>",
            ]
            link_names.append(child)
            link_bodies[child] = []
            current = child
            fixed = _dh_fixed(a, alpha, d)
        else:
            fixed = fixed @ _rot_z(offset) @ _dh_fixed(a, alpha, d)

    link_bodies[current] += _link_visual(fixed[:3, 3])
    link_names.append("tool0")
    link_bodies["tool0"] = []
    joint_blocks += [
        '  <joint name="tool0_fixed" type="fixed">',
        "    <!-- TCP (gripper centre). The gripper J5 opens/closes here but does not move tool0. -->",
        f'    <parent link="{current}"/>',
        '    <child link="tool0"/>',
        f"    {_origin(fixed)}",
        "  </joint>",
    ]

    for name in link_names:
        body = link_bodies[name] + _inertial(dynamics.get(name))
        if body:
            lines += [f'  <link name="{name}">', *body, "  </link>"]
        else:
            lines.append(f'  <link name="{name}"/>')
    lines += joint_blocks
    lines.append("</robot>")
    return "\n".join(lines) + "\n"


def _inertial(spec) -> list:
    """Optional inertial from robot.yaml ``dynamics.<link>``:
    {mass_kg, com_m: [x,y,z], inertia: [ixx, iyy, izz, ixy, ixz, iyz]}."""
    if not spec:
        return []
    com = spec.get("com_m", [0, 0, 0])
    ixx, iyy, izz, ixy, ixz, iyz = spec.get("inertia", [1e-6, 1e-6, 1e-6, 0, 0, 0])
    return [
        "    <inertial>",
        f'      <origin xyz="{_fmt(com)}" rpy="0 0 0"/>',
        f'      <mass value="{spec["mass_kg"]:.9g}"/>',
        f'      <inertia ixx="{ixx:.9g}" ixy="{ixy:.9g}" ixz="{ixz:.9g}" '
        f'iyy="{iyy:.9g}" iyz="{iyz:.9g}" izz="{izz:.9g}"/>',
        "    </inertial>",
    ]


# ─── Verification ───────────────────────────────────────────────────────────

def urdf_fk(urdf_text: str, q_by_joint: dict) -> np.ndarray:
    """base_link → tool0 transform (metres) by walking the URDF chain."""
    root = ET.fromstring(urdf_text)
    by_child = {j.find("child").get("link"): j for j in root.findall("joint")}
    chain = []
    link = "tool0"
    while link in by_child:
        j = by_child[link]
        chain.append(j)
        link = j.find("parent").get("link")
    T = np.eye(4)
    for j in reversed(chain):
        o = j.find("origin")
        xyz = [float(v) for v in o.get("xyz").split()]
        r, p, y = [float(v) for v in o.get("rpy").split()]
        cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
        O = np.eye(4)
        O[:3, :3] = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]]) @ \
            np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]]) @ \
            np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
        O[:3, 3] = xyz
        T = T @ O
        if j.get("type") == "revolute":
            T = T @ _rot_z(math.degrees(q_by_joint[j.get("name")]))
    return T


def verify(urdf_text: str, cfg: dict, samples: int = 200, seed: int = 0) -> float:
    """Max TCP position error (mm) between the URDF and forward_kinematics()."""
    rng = np.random.default_rng(seed)
    joints = cfg["joints"]
    worst = 0.0
    for _ in range(samples):
        servo_deg = [rng.uniform(j["min_angle"], j["max_angle"]) for j in joints]
        q = {j["name"].lower(): math.radians(a - SERVO_ZERO_DEG)
             for j, a in zip(joints, servo_deg) if config.joint_type(j) == "revolute"}
        T_urdf = urdf_fk(urdf_text, q)
        T_fk = forward_kinematics(servo_deg, cfg)
        worst = max(worst, float(np.linalg.norm(T_urdf[:3, 3] / MM - T_fk[:3, 3])))
        if not np.allclose(T_urdf[:3, :3], T_fk[:3, :3], atol=1e-8):
            raise AssertionError("URDF orientation disagrees with forward_kinematics()")
    return worst


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the checked-in URDF is stale or disagrees with forward_kinematics()")
    args = parser.parse_args()

    cfg = config.load_file(config.CONFIG_PATH)
    text = build_urdf(cfg)
    err = verify(text, cfg)
    if err > 1e-6:
        print(f"URDF weicht von forward_kinematics() ab: {err:.3g} mm", file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"{OUTPUT.relative_to(ROOT)} ist veraltet – "
                  "python3 tools/generate_urdf.py ausführen", file=sys.stderr)
            return 1
        print(f"OK: URDF aktuell, max. TCP-Abweichung {err:.2e} mm")
        return 0

    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(text)
    print(f"{OUTPUT.relative_to(ROOT)} geschrieben (max. TCP-Abweichung {err:.2e} mm)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
